import React from 'react';

const TermsOfService = () => (
    <div className="space-y-4 text-sm text-gray-700">
        <h3 className="font-bold text-gray-900">1. Acceptance of Terms</h3>
        <p>By accessing and using Dr. Console, you accept and agree to be bound by the terms and provision of this agreement.</p>

        <h3 className="font-bold text-gray-900">2. Description of Service</h3>
        <p>Dr. Console provides AI-driven health informational services. You acknowledge that this information is generated by artificial intelligence and may contain errors.</p>

        <h3 className="font-bold text-gray-900">3. User Conduct</h3>
        <p>You agree to use this service for lawful purposes only. You are prohibited from uploading any content that is illegal, offensive, or violates the rights of others.</p>

        <h3 className="font-bold text-gray-900">4. Limitation of Liability</h3>
        <p>Dr. Console and its creators shall not be liable for any damages arising out of or regarding the use of this service.</p>
    </div>
);

export default TermsOfService;
